### ISSUE TITLE
Nunjucks

### ISSUE THREAD

**Issue by Hirbod** [tomaszbujnowicz/frontie-webpack#5]
Hi, great starter pack. Did you consider a version with nunjucks instead of twig?

**Comment by tomaszbujnowicz** [comment]
Hi, thanks for your kind words. 
I don't use that boilerplate anymore but I think it should be relatively easy to implement nunjucks (or any other template language engine) instead of twig. I am quite occupied these days and don't have time for that right now so I hope you can figure this one out by yourself ;)
